version: "3"

services:
    db:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        ports:
            - 4306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: financeiro
            MYSQL_USER: financeiro
            MYSQL_PASSWORD: financeiro

    api:
        depends_on:
            - db
        build: ./api/
        volumes:
            - "./:/app/"
        ports:
            - "8080:8080"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=financeiro
            - DB_USERNAME=financeiro
            - DB_PASSWORD=financeiro
